epics-gateways:
  # for personal namespaces we don't have host network permission
  hostNetwork: false
  # switch to developer image for debugging
  image: ghcr.io/epics-containers/epics-gateways-developer:2025.11.1
